[package]
name = "smol-rgb"
version = "0.1.0"
authors = ["Jonathan Spira <jjspira@gmail.com>"]
edition = "2018"

[features]
default = ["std"]
std = []

[dependencies]
libm = { version = "0.2.1", optional = true }
bytemuck = { version = "1.5", optional = true }
serde = { version = "1.0", optional = true }

[dev-dependencies]
static_assertions = "1.1"
serde_yaml = "0.8"
serde_json = "1.0"
bincode = "1.3.2"