[package]
name = "smol-rgb"
version = "0.1.2"
authors = ["Jonathan Spira <jjspira@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sanbox-irl/smol-rgb"
description = "A smol library for (s)Rgb color handling."
categories = ["rendering::data-formats", "game-development"]

[features]
default = ["std"]
std = []

[dependencies]
libm = { version = "0.2.1", optional = true }
bytemuck = { version = "1.5", optional = true }
serde = { version = "1.0", optional = true }

[dev-dependencies]
static_assertions = "1.1"
serde_yaml = "0.8"
serde_json = "1.0"
bincode = "1.3.2"